version: "3"

services:
  broker:
    image: eclipse-mosquitto
    networks:
      - localnet
    ports:
      - "1883:1883"
    volumes:
      - "./mosquitto:/mosquitto"
    restart: on-failure

  nodered:
    depends_on:
      - broker
    image: nodered/node-red
    networks:
      - localnet
    ports:
      - "1880:1880"
    volumes:
      - "./node-red:/data"
    user: "0"
    restart: always

networks:
  localnet:
